### ISSUE TITLE
Updated for Statamic Latest Version

### ISSUE THREAD

**Issue by bgarrant** [addisonhall/antlers-statamic-sublime-syntax#1]
Is this add-on updated with latest Systemic 2.7.3 tags like the Atom and VS Code add-ons?  We tried to use it and the syntax highlighting does not look correct in Sublime 3143.  I colleague said he saw a regex error in one of the strings but I have not had a chance to look yet myself.

**Comment by bgarrant** [comment]
![screen shot 2018-01-04 at 4 55 46 pm](https://user-images.githubusercontent.com/2436728/34586010-2c53af26-f170-11e7-857b-0d82060bb81f.png)

**Comment by bgarrant** [comment]
That is a whole lot of red

**Comment by addisonhall** [comment]
I'm afraid that I don't use Sublime Text any longer so I haven't updated this version in quite a while. If I get a chance I'll see if I can bring it up to speed.

**Comment by bgarrant** [comment]
No worries. I will have the team use Atom then. Is that most current?

**Comment by addisonhall** [comment]
Yep. [Atom](https://atom.io/packages/language-antlers) and [VS Code](https://marketplace.visualstudio.com/items?itemName=ahdesign.language-antlers) are pretty up-to-date.

**Comment by bgarrant** [comment]
Have you had a chance to update the Sublime plugin by chance? If you can update that one, I am going to try to make a plugin for PHPStorm with it as it requires a textmate bundle. I do not know much about TM bundles or I would do it.

I posted this question in Slack also.  Thanks in advance.

**Comment by addisonhall** [comment]
I'll see what I can do over the next few days. I'm pretty sure I can convert the VS Code json to tmLanguage and we'll be good to go.

**Comment by bgarrant** [comment]
@addisonhall Thanks so much.  :)

**Comment by bgarrant** [comment]
Looks like this may help https://github.com/Togusa09/vscode-tmlanguage/blob/master/readme.md

**Comment by bgarrant** [comment]
Did the export work? I am back on Sublime and this would really help. I would update it but don’t know how.

**Comment by addisonhall** [comment]
I just pushed out an update. See how that works for you. Thanks!

**Comment by bgarrant** [comment]
I will try to out.  Thanks so much.  There are three ST3 users at our office and I will also try to import to PHPStorm.  :)

**Comment by bgarrant** [comment]
Works great.  Thank you so much!

**Comment by addisonhall** [comment]
Hooray! That's great to hear. Thanks for testing.
